### ISSUE TITLE
More pictures and PCB available?

### ISSUE THREAD

**Issue by spotlesscoder** [craigyjp/Poly-Zero-8-voice-Polysynth#1]
Hi,

do you have more pictures of the inner life of the device?
Looks really promising - I would love to build one for myself - do you have gerber files for the PCB(s) inside?

**Comment by craigyjp** [comment]
Hi, I don't have gerbers because it's on proto boards and not PCB's, all hand wired for the 7 cards and the mother board.

**Comment by craigyjp** [comment]
I've just added some photos

**Comment by craigyjp** [comment]
I hope thats enough info

**Comment by spotlesscoder** [comment]
Holy hell that must have been a lot of work :O

Thanks for sharing this, loving it :)
